### ISSUE TITLE
Allow adding nullable objects

### ISSUE THREAD

**Issue by lukas-krecan** [ncomet/koson#13]
**Describe the solution you'd like**
I want to construct object like this. Note the `status` field which should be null if `status` is null, an object otherwise.

```
        obj {
            "data" to obj {
                "name" to name
                "description" to description
                "status" to status?.let { status ->
                    obj {
                        "id" to status.id
                        "name" to status.name
                    }
                }
            }
        }
```
Due to `infix fun String.to(value: ObjectType)` not accepting nullable type, the status value gets serialized as String which is surprising. It would make sense to me  change the signature to `infix fun String.to(value: ObjectType?)`

**Describe alternatives you've considered**
Create my own extension method

**Comment by ncomet** [comment]
I'm working on it. If I understood you correctly, now we will have these signature:

```
interface CustomKoson {
    fun serialize(): KosonType
}
```

It seems more intuitive.

Also, we allow for null CustomKoson : 

```
infix fun String.to(value: CustomKoson?) {
    objectType.values[this] = if (value == null) NullType else CustomKosonType(value)
}
```

The tests I'm working on, given the following CustomKoson : 

```
    data class Status(val id: String, val name: String) : CustomKoson {
        override fun serialize() = obj {
            "id" to id
            "name" to name
        }
    }
```

You'll be able to write :

```
@Test
    fun `should work on not null nullable customtypes`() {
        val name = "myName"
        val description = "desc"
        val status = Status("OK", "Nice")

        val representation = obj {
            "data" to obj {
                "name" to name
                "description" to description
                "status" to status
            }
        }.toString()

        assertThat(representation).isEqualTo("""{"data":{"name":"myName","description":"desc","status":{"id":"OK","name":"Nice"}}}""")
    }
```

and also

```
@Test
    fun `should work on null customtypes`() {
        val name = "myName"
        val description = "desc"
        val status: Status? = null

        val representation = obj {
            "data" to obj {
                "name" to name
                "description" to description
                "status" to status
            }
        }.toString()

        assertThat(representation).isEqualTo("""{"data":{"name":"myName","description":"desc","status":null}}""")
    }
```

**Comment by lukas-krecan** [comment]
Hi, I do not want to extend your types if I do not have to. Anyway, at the end we decided not to use Koson so I feel I can't provide the feedback anymore.

**Comment by ncomet** [comment]
I understand completely, however you gave us an improvement idea ;) Thanks for that.

**Comment by matsjoe** [comment]
Any chance of this happening? It should only take 2 lines of code to change and will fix in my opinion a huge bug. At the moment I have to add a nullable array which is not possible. Or any time for a version 1.2.0 release so I atleast can use the CustomKoson interface?

**Comment by ncomet** [comment]
Sorry I had a gpg (signing) problem while releasing version 1.2.0. Don't know why I need to investigate.
