### ISSUE TITLE
Support Multiplatform

### ISSUE THREAD

**Issue by mkrussel77** [ncomet/koson#15]
**Describe the solution you'd like**
Would like to see artifacts created to support Kotlin native and Kotlin JS

**Describe alternatives you've considered**
Not use this library.

**Additional context**
Currently this library cannot be used in a Kotlin Multiplatform project.

**Comment by ncomet** [comment]
At the moment it is not the aim of the library to support other platform than JVM. 

Moreover, there already exists a function in the JS SDK addressing the JS platform : https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.js/json.html
