### ISSUE TITLE
Release koson 1.2.0 with latest changes

### ISSUE THREAD

**Issue by Yunir** [ncomet/koson#17]
**Describe the solution you'd like**
koson 1.2.0 with breaking-change feature is available through Maven Central.

**Additional context**
For now, the latest release is 1.1.0 that was published almost a year ago.

**Comment by Farsen976** [comment]
Yes, of course. We'll take a look with @ncomet.

**Comment by ncomet** [comment]
I don't know if I can release it. We had a public certificate issue, that needs to be fixed to release again.

**Comment by Farsen976** [comment]
Hello @Yunir,
we've just released Koson 1.2.0 version. 
We still have issues with gpg key, but we are working on it. 

Regards.
