### ISSUE TITLE
[BUG] Unsigned int gets rendered with doublequotes.

### ISSUE THREAD

**Issue by Pival81** [ncomet/koson#19]
**Describe the bug**
if I pass a mutablelistof UInt to the arr function, the numbers get rendered with double quotes.

**To Reproduce**
`var hashes = mutableListOf<UInt>()`
\*hashes gets populated\*
`val json = obj {
            "fingeprints" to arr[hashes]
        }`

This is the result:
`{"fingeprints":["2037562781","950962331","2098967947","1923394747","1208381800","4208511036","1189087403","3112664858","1927750889","132780196","2939054441","2344180314","700332151","69589181","4073557974","3186705234","4247051032","3424319008","527761311","1663259258","3147221039","3051920250","1326824199","3058542917","2645504695","4036556600","2546524333","2263235725","2674739867","2456791220","960878632","2079223742","3635781753","1156837785","2760206313","2429064344","2561881248","1647323103","2814931268","2940918666","3315557568","928719472","357764832","4116341275","3646669765","985130708","2077870799","1339366238","3556613806","1477774991","3804689212","1278380072","4017976554","1524017603","30853613","3391923374","4276519539","15669106","2369374914","3606401570","102104902","3296753719","4079501098","3431674564","1951927590","893448873","663145740","3366003449","385205199","3670568557","2604776347","2158415375","3373359416","2050253455","2436194208","2758339561","2480667074","649963734","1755255769","127253762","387064965","3044272212","3090990458","752442057","957833589","679359278","3227065054","2234355340","1769408380","889307551","2131771166","517868395","3688932837","3974104388","2476903427","1899009469","1099974475","4115732889","3191820527","906225403","3026785728","622213382","3640084743","1323756321","1357893814","1029740924","2134134003","2844918678","3052389056","42535972","1751938952","2859414566","2022685873","12823422","1053708721","1065578237","537556958","3409186676","58555158","3665289799","4229284541","4163821524","3375441244","1145034958","1309992467","1957644973","3399911541","2810798110","3368764801","285741512","1264768531","2846168077","4288924319","563839039","264714097","1130724094","2265859872","4068050300","2815907424","3293312934","861772466","1325613941","799467220","2580984741","195298617","528336969","3824057421","3597605255","3096980174","424401967","401018132","4127400724","1284405660","2862833350","40853236","3489152163","919757452","724624531","1703043317","2117407503","473856560","3501978731","1782350993","3280433554","947793980","2798396102","3594410772","1698652667","2910837341","3215073064","3076552374","4294806470","595501837","1893256567","2309391079","1116314815","2954177313","3940998357","2136552890","2505436273","1220664206","2767594484","2935534804","2664592608","2438960667","2906374988","318003884","1286889796","1281292797","152655390","493026423","2644731150","3094578446","830747102","2661815445","2972814032","1607642850","1577413405","1428117145","3654039533","727191017","3052545616","1964344708","1565720065","712648954","1015267246","1578117200","2622721057","416328819","729022150","2149204761","2094495496","790351058","3719101601","2159395981","846913390","2774381824","594617711","2199747633","1768893200","354033785","2075832610","1725348470","1608257474","2608670190","294323465","1449441659","2388595289","3692313526","1083589873","2926245632","1072171054","660240547","1626037618","2934385522","1453113073","2764134718"]}`

**Expected behavior**
I'd expect the unsigned integers to be trated like numbers, without displaying double quotes.

**Comment by Farsen976** [comment]
Hello @Pival81, 

thank you for your bug report. We will take care of it as soon as possible.

Have a great day !

**Comment by Farsen976** [comment]
Hi @Pival81, 

did you try the CustomKoson ? I think it will resolve your issue. Let me know if it works.
