### ISSUE TITLE
[BUG] build fail with jdk 17

### ISSUE THREAD

**Issue by McFoggy** [ncomet/koson#23]
while trying to update to jdk 17 for last defect resolution, we faced an issue.
See build results https://github.com/lectra-tech/koson/actions/runs/3412350907

**Comment by Farsen976** [comment]
#24 
Updating nexus-staging-maven-plugin to 1.6.13 should fix this issue

**Comment by McFoggy** [comment]
closed with 6c08652de4c85a2280c8ddee67c4503784747d83
